# Generated by Django 4.1.7 on 2023-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_ipcr_form_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr_form_model',
            name='IPCR_Submitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
