# Generated by Django 4.1.7 on 2023-05-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_ipcr_form_model_ipcr_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipmt_form_model',
            old_name='MidtermAnswerKey_Accomplished',
            new_name='AnswerKey_Accomplished',
        ),
        migrations.RenameField(
            model_name='ipmt_form_model',
            old_name='FinaltermAnswerKey_Accomplished',
            new_name='TOSRubrics_Accomplished',
        ),
        migrations.RenameField(
            model_name='ipmt_form_model',
            old_name='MidtermTestQuestions_Accomplished',
            new_name='TestQuestions_Accomplished',
        ),
        migrations.RemoveField(
            model_name='ipmt_form_model',
            name='FinaltermTOSRubrics_Accomplished',
        ),
        migrations.RemoveField(
            model_name='ipmt_form_model',
            name='FinaltermTestQuestions_Accomplished',
        ),
        migrations.RemoveField(
            model_name='ipmt_form_model',
            name='MidtermTOSRubrics_Accomplished',
        ),
    ]
