# Generated by Django 4.1.7 on 2023-05-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forms', '0028_ipcr_form_model_department_ipcr_form_model_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmt_form_model',
            name='department',
            field=models.ManyToManyField(null=True, to='auth.group'),
        ),
    ]
