# Generated by Django 4.1.7 on 2023-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forms', '0029_ipmt_form_model_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr_form_model',
            name='department',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model',
            name='department',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
