# Generated by Django 4.1.7 on 2023-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_remove_ipcr_form_model_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmt_form_model',
            name='department',
        ),
        migrations.AddField(
            model_name='ipcr_form_model_submitted',
            name='department',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
