# Generated by Django 4.1.7 on 2023-05-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_remove_ipmt_form_model_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr_form_model_submitted',
            name='user_fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
