# Generated by Django 4.1.7 on 2023-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_ipcr_form_model_submitted_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCR_Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_Remarks', models.CharField(max_length=100)),
                ('CourseGuide_Remarks', models.CharField(max_length=100)),
                ('SLM_Remarks', models.CharField(max_length=100)),
                ('SubjectAreas_Remarks', models.CharField(max_length=100)),
                ('AttendanceSheet_Remarks', models.CharField(max_length=100)),
                ('ClassRecord_Remarks', models.CharField(max_length=100)),
                ('TeachingEffectiveness_Remarks', models.CharField(max_length=100)),
                ('ClassroomObservation_Remarks', models.CharField(max_length=100)),
                ('MidtermTOSRubrics_Remarks', models.CharField(max_length=100)),
                ('FinaltermTOSRubrics_Remarks', models.CharField(max_length=100)),
                ('MidtermTestQuestions_Remarks', models.CharField(max_length=100)),
                ('FinaltermTestQuestions_Remarks', models.CharField(max_length=100)),
                ('MidtermAnswerKey_Remarks', models.CharField(max_length=100)),
                ('FinaltermAnswerKey_Remarks', models.CharField(max_length=100)),
                ('GradingSheet_Remarks', models.CharField(max_length=100)),
                ('StudentAdviced_Remarks', models.CharField(max_length=100)),
                ('AccomplishmentReport_Remarks', models.CharField(max_length=100)),
                ('ResearchProposalSubmitted_Remarks', models.CharField(max_length=100)),
                ('ResearchImplemented_Remarks', models.CharField(max_length=100)),
                ('ResearchPresented_Remarks', models.CharField(max_length=100)),
                ('ResearchPublished_Remarks', models.CharField(max_length=100)),
                ('ApprovedIPRights_Remarks', models.CharField(max_length=100)),
                ('ResearchUtilized_Remarks', models.CharField(max_length=100)),
                ('NumberOfCitations_Remarks', models.CharField(max_length=100)),
                ('ExtensionProposalSubmitted_Remarks', models.CharField(max_length=100)),
                ('PersonTrained_Remarks', models.CharField(max_length=100)),
                ('PersonAvailedRatedGood_Remarks', models.CharField(max_length=100)),
                ('PersonTrainedRatedGood_Remarks', models.CharField(max_length=100)),
                ('TechnicalAdvice_Remarks', models.CharField(max_length=100)),
                ('AccomplishmentReportDeligatedAssignment_Remarks', models.CharField(max_length=100)),
                ('FlagRaisingAttendance_Remarks', models.CharField(max_length=100)),
                ('FlagLoweringAttendance_Remarks', models.CharField(max_length=100)),
                ('WellnessProgramAttendance_Remarks', models.CharField(max_length=100)),
                ('SchoolCelebrationAttendance_Remarks', models.CharField(max_length=100)),
                ('TrainingAttendance_Remarks', models.CharField(max_length=100)),
                ('FacultyMeetingAttendance_Remarks', models.CharField(max_length=100)),
                ('AccreditationAttendance_Remarks', models.CharField(max_length=100)),
                ('SpiritualActivityAttendance_Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
