# Generated by Django 4.1.7 on 2023-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0036_ipcr_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr_remarks',
            name='reviewer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
