# Generated by Django 4.1.7 on 2023-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0037_ipcr_remarks_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr_form_model',
            name='approver',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
