# Generated by Django 4.1.7 on 2023-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_ipcr_form_model_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr_form_model',
            name='approver',
        ),
        migrations.AddField(
            model_name='ipcr_form_model_submitted',
            name='approver',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
