# Generated by Django 4.1.7 on 2023-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0042_ipmt_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_AccomplishmentReport_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_AccreditationAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_AnswerKey_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ApprovedIPRights_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_AttendanceSheet_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ClassRecord_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ClassroomObservation_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_CourseGuide_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ExtensionProposalSubmitted_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_FacultyMeetingAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_FlagLoweringAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_FlagRaisingAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_GradingSheet_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_NumberOfCitations_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_PersonAvailedRatedGood_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_PersonTrainedRatedGood_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_PersonTrained_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ResearchImplemented_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ResearchPresented_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ResearchProposalSubmitted_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ResearchPublished_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_ResearchUtilized_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_SLM_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_SchoolCelebrationAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_SpiritualActivityAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_StudentAdviced_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_SubjectAreas_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_TOSRubrics_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_TeachingEffectiveness_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_TechnicalAdvice_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_TestQuestions_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_TrainingAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_WellnessProgramAttendance_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='Remarks_syllabus_Accomplished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_remarks',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
