# Generated by Django 4.1.7 on 2023-06-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0043_alter_ipmt_remarks_accomplishmentreportdeligatedassignment_accomplished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipmt_remarks',
            old_name='IPCR_Submitted',
            new_name='IPMT_Submitted',
        ),
    ]
