# Generated by Django 4.1.7 on 2023-06-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0045_remove_ipmt_remarks_accomplishmentreportdeligatedassignment_accomplished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_1',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_10',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_11',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_12',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_2',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_3',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_4',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_5',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_6',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_7',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_8',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='AccomplishmentReportDeligatedAssignment_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='AccomplishmentReport_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='AccreditationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='AnswerKey_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ApprovedIPRights_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='AttendanceSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ClassRecord_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ClassroomObservation_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='CourseGuide_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ExtensionProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='FacultyMeetingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='FlagLoweringAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='FlagRaisingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='GradingSheet_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='NumberOfCitations_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='PersonAvailedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='PersonTrainedRatedGood_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='PersonTrained_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ResearchImplemented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ResearchPresented_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ResearchProposalSubmitted_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ResearchPublished_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='ResearchUtilized_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='SLM_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='SchoolCelebrationAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='SpiritualActivityAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='StudentAdviced_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='SubjectAreas_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='TOSRubrics_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='TeachingEffectiveness_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='TechnicalAdvice_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='TestQuestions_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='TrainingAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='WellnessProgramAttendance_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmt_form_model_submitted_9',
            name='syllabus_Accomplished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
