# Generated by Django 4.1.7 on 2023-08-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0046_alter_ipmt_form_model_submitted_1_accomplishmentreportdeligatedassignment_accomplished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcr_form_model',
            old_name='IPCR_Submitted',
            new_name='IPCR_Saved',
        ),
    ]
