# Generated by Django 4.1.7 on 2023-06-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0047_rename_ipcr_submitted_ipcr_form_model_ipcr_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr_form_model',
            name='IPCR_Saved',
        ),
    ]
