# Generated by Django 4.1.7 on 2023-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0048_remove_ipcr_form_model_ipcr_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr_form_model',
            name='IPCR_Saved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
