# Generated by Django 4.1.7 on 2023-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0049_ipcr_form_model_ipcr_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr_rating',
            name='IPCR_Submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipcr_remarks',
            name='IPCR_Submitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
