# Generated by Django 4.1.7 on 2023-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='new_post',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
