from django.db import models
from django.contrib.auth.models import User, Group
# Create your models here.


class IPCR_Form_model (models.Model):
    syllabus_Target = models.IntegerField(default = 0, null = True, blank = True)
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Target = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Target = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Target = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Target = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Target = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Target = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Target = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_Target = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_Target = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_Target = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_Target = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_Target = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_Target = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Target = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Target = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Target = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Target = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Target = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Target = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Target = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Target = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Target = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Target = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Target = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Saved = models.DateField(null=True, blank=True)
    IPCR_Deadline = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=255)
    

class IPCR_Form_model_submitted (models.Model):
    syllabus_Target = models.IntegerField(default = 0, null = True, blank = True)
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Target = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Target = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Target = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Target = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Target = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Target = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Target = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_Target = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_Target = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_Target = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_Target = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_Target = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_Target = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Target = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Target = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Target = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Target = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Target = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Target = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Target = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Target = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Target = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Target = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Target = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Target = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Target = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Deadline = models.DateField(null=True, blank=True)
    IPCR_Submitted = models.DateField(null=True, blank=True)
    department = models.CharField(max_length=255)
    user_fullname = models.CharField(max_length=255)
    approver = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

class IPCR_Remarks (models.Model):
    syllabus_Remarks = models.CharField(max_length=100)
    CourseGuide_Remarks = models.CharField(max_length=100)
    SLM_Remarks = models.CharField(max_length=100)
    SubjectAreas_Remarks = models.CharField(max_length=100)
    AttendanceSheet_Remarks = models.CharField(max_length=100)
    ClassRecord_Remarks = models.CharField(max_length=100)
    TeachingEffectiveness_Remarks = models.CharField(max_length=100)
    ClassroomObservation_Remarks = models.CharField(max_length=100)
    MidtermTOSRubrics_Remarks = models.CharField(max_length=100)
    FinaltermTOSRubrics_Remarks = models.CharField(max_length=100)
    MidtermTestQuestions_Remarks = models.CharField(max_length=100)
    FinaltermTestQuestions_Remarks = models.CharField(max_length=100)
    MidtermAnswerKey_Remarks = models.CharField(max_length=100)
    FinaltermAnswerKey_Remarks = models.CharField(max_length=100)
    GradingSheet_Remarks = models.CharField(max_length=100)
    StudentAdviced_Remarks = models.CharField(max_length=100)
    AccomplishmentReport_Remarks = models.CharField(max_length=100)
    ResearchProposalSubmitted_Remarks = models.CharField(max_length=100)
    ResearchImplemented_Remarks = models.CharField(max_length=100)
    ResearchPresented_Remarks = models.CharField(max_length=100)
    ResearchPublished_Remarks = models.CharField(max_length=100)
    ApprovedIPRights_Remarks = models.CharField(max_length=100)
    ResearchUtilized_Remarks = models.CharField(max_length=100)
    NumberOfCitations_Remarks = models.CharField(max_length=100)
    ExtensionProposalSubmitted_Remarks = models.CharField(max_length=100)
    PersonTrained_Remarks = models.CharField(max_length=100)
    PersonAvailedRatedGood_Remarks = models.CharField(max_length=100)
    PersonTrainedRatedGood_Remarks = models.CharField(max_length=100)
    TechnicalAdvice_Remarks = models.CharField(max_length=100)
    AccomplishmentReportDeligatedAssignment_Remarks = models.CharField(max_length=100)
    FlagRaisingAttendance_Remarks = models.CharField(max_length=100)
    FlagLoweringAttendance_Remarks = models.CharField(max_length=100)
    WellnessProgramAttendance_Remarks = models.CharField(max_length=100)
    SchoolCelebrationAttendance_Remarks = models.CharField(max_length=100)
    TrainingAttendance_Remarks = models.CharField(max_length=100)
    FacultyMeetingAttendance_Remarks = models.CharField(max_length=100)
    AccreditationAttendance_Remarks = models.CharField(max_length=100)
    SpiritualActivityAttendance_Remarks = models.CharField(max_length=100)
    
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    reviewer = models.CharField(max_length=100)

class IPCR_Rating (models.Model):
    syllabus_QTY = models.IntegerField(default = 0, null = True, blank = True)
    syllabus_QLE = models.IntegerField(default = 0, null = True, blank = True)
    syllabus_T = models.IntegerField(default = 0, null = True, blank = True)
    syllabus_A = models.IntegerField(default = 0, null = True, blank = True)
    
    CourseGuide_QTY = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_QLE = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_T = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_A = models.IntegerField(default = 0, null = True, blank = True)
    
    SLM_QTY = models.IntegerField(default = 0, null = True, blank = True)
    SLM_QLE = models.IntegerField(default = 0, null = True, blank = True)
    SLM_T = models.IntegerField(default = 0, null = True, blank = True)
    SLM_A = models.IntegerField(default = 0, null = True, blank = True)
    
    SubjectAreas_QTY = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_QLE = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_T = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_A = models.IntegerField(default = 0, null = True, blank = True)
    
    AttendanceSheet_QTY = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_QLE = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_T = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ClassRecord_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_T = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_A = models.IntegerField(default = 0, null = True, blank = True)
    
    TeachingEffectiveness_QTY = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_QLE = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_T = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ClassroomObservation_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_T = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_A = models.IntegerField(default = 0, null = True, blank = True)
    
    MidtermTOSRubrics_QTY = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_QLE = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_T = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTOSRubrics_A = models.IntegerField(default = 0, null = True, blank = True)
    
    FinaltermTOSRubrics_QTY = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_QLE = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_T = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTOSRubrics_A = models.IntegerField(default = 0, null = True, blank = True)
    
    MidtermTestQuestions_QTY = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_QLE = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_T = models.IntegerField(default = 0, null = True, blank = True)
    MidtermTestQuestions_A = models.IntegerField(default = 0, null = True, blank = True)
    
    FinaltermTestQuestions_QTY = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_QLE = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_T = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermTestQuestions_A = models.IntegerField(default = 0, null = True, blank = True)
    
    MidtermAnswerKey_QTY = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_QLE = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_T = models.IntegerField(default = 0, null = True, blank = True)
    MidtermAnswerKey_A = models.IntegerField(default = 0, null = True, blank = True)
    
    FinaltermAnswerKey_QTY = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_QLE = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_T = models.IntegerField(default = 0, null = True, blank = True)
    FinaltermAnswerKey_A = models.IntegerField(default = 0, null = True, blank = True)
    
    GradingSheet_QTY = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_QLE = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_T = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_A = models.IntegerField(default = 0, null = True, blank = True)
    
    StudentAdviced_QTY = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_QLE = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_T = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_A = models.IntegerField(default = 0, null = True, blank = True)
    
    AccomplishmentReport_QTY = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_QLE = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_T = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ResearchProposalSubmitted_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_T = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ResearchImplemented_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_T = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ResearchPresented_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_T = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ResearchPublished_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_T = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ApprovedIPRights_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_T = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ResearchUtilized_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_T = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_A = models.IntegerField(default = 0, null = True, blank = True)
    
    NumberOfCitations_QTY = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_QLE = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_T = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_A = models.IntegerField(default = 0, null = True, blank = True)
    
    ExtensionProposalSubmitted_QTY = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_QLE = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_T = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_A = models.IntegerField(default = 0, null = True, blank = True)
    
    PersonTrained_QTY = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_QLE = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_T = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_A = models.IntegerField(default = 0, null = True, blank = True)
    
    PersonAvailedRatedGood_QTY = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_QLE = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_T = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_A = models.IntegerField(default = 0, null = True, blank = True)
    
    PersonTrainedRatedGood_QTY = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_QLE = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_T = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_A = models.IntegerField(default = 0, null = True, blank = True)
    
    TechnicalAdvice_QTY = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_QLE = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_T = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_A = models.IntegerField(default = 0, null = True, blank = True)
    
    AccomplishmentReportDeligatedAssignment_QTY = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_QLE = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_T = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_A = models.IntegerField(default = 0, null = True, blank = True)
    
    FlagRaisingAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    FlagLoweringAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    WellnessProgramAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    SchoolCelebrationAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    TrainingAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    FacultyMeetingAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    AccreditationAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
    
    SpiritualActivityAttendance_QTY = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_QLE = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_T = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_A = models.IntegerField(default = 0, null = True, blank = True)
   
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model (models.Model):
    syllabus_Accomplished = models.IntegerField(null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(null = True, blank = True)
    SLM_Accomplished = models.IntegerField(null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(null = True, blank = True)
    
    IPCR_Saved = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

class IPMT_Remarks (models.Model):
    Remarks_syllabus_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_CourseGuide_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_SLM_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_SubjectAreas_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_AttendanceSheet_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ClassRecord_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_TeachingEffectiveness_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ClassroomObservation_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_TOSRubrics_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_TestQuestions_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_AnswerKey_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_GradingSheet_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_StudentAdviced_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_AccomplishmentReport_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ResearchProposalSubmitted_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ResearchImplemented_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ResearchPresented_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ResearchPublished_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ApprovedIPRights_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ResearchUtilized_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_NumberOfCitations_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_ExtensionProposalSubmitted_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_PersonTrained_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_PersonAvailedRatedGood_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_PersonTrainedRatedGood_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_TechnicalAdvice_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_AccomplishmentReportDeligatedAssignment_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_FlagRaisingAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_FlagLoweringAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_WellnessProgramAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_SchoolCelebrationAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_TrainingAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_FacultyMeetingAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_AccreditationAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    Remarks_SpiritualActivityAttendance_Accomplished = models.CharField(max_length=100, null = True, blank = True)
    
    IPMT_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    

class IPMT_Form_model_submitted_1 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_2 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)   
    
class IPMT_Form_model_submitted_3 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_4 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_5 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_6 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_7 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_8 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_9 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_10 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_11 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
class IPMT_Form_model_submitted_12 (models.Model):
    syllabus_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    CourseGuide_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SLM_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SubjectAreas_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AttendanceSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassRecord_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TeachingEffectiveness_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ClassroomObservation_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TOSRubrics_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TestQuestions_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AnswerKey_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    GradingSheet_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    StudentAdviced_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReport_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchImplemented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPresented_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchPublished_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ApprovedIPRights_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ResearchUtilized_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    NumberOfCitations_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    ExtensionProposalSubmitted_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrained_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonAvailedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    PersonTrainedRatedGood_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TechnicalAdvice_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccomplishmentReportDeligatedAssignment_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagRaisingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FlagLoweringAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    WellnessProgramAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SchoolCelebrationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    TrainingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    FacultyMeetingAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    AccreditationAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    SpiritualActivityAttendance_Accomplished = models.IntegerField(default = 0, null = True, blank = True)
    
    IPCR_Submitted = models.DateField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)